### ISSUE TITLE
importjs process not running when outside of react directory

### ISSUE THREAD

**Issue by deltaskelta** [Galooshi/vim-import-js#24]
this is probably a simple fix but I cannot see what is going on. 

I installed the `vim-import-js` plugin and added a line in my vimrc to run it on the save of javascript files. 

    au BufWritePre *.js :ImportJSFix

I then noticed that if I was outside of the react directory that I was working in, and I tried to edit a normal file with vim, I would get an error that says 

    importjs process not running

how is it finding or running the process from inside of the react project but not from the outside (I have installed importjs globally)

**Comment by trotzig** [comment]
I had to brush up a little on how everything is setup, but after some twiddling I managed to reproduce things. I think the culprit is this: 

```
⨠ importjs start < import-js/IMPORTJS
ImportJS (v2.6.0) DAEMON active. Logs will go to: /var/folders/1l/_t6tm7195nd53936tsvh2pc
r0000gn/T/importjs.log
/Users/henrictrotzig/import-js/build/findProjectRoot.js:20
    throw new Error('No project root found, looking for a directory with a package.json f
ile.');
    ^

Error: No project root found, looking for a directory with a package.json file.
    at findRecursive (/Users/henrictrotzig/import-js/build/findProjectRoot.js:20:11)
    at findRecursive (/Users/henrictrotzig/import-js/build/findProjectRoot.js:29:10)
    at findRecursive (/Users/henrictrotzig/import-js/build/findProjectRoot.js:29:10)
    at findProjectRoot (/Users/henrictrotzig/import-js/build/findProjectRoot.js:41:10)
    at Interface.<anonymous> (/Users/henrictrotzig/import-js/build/daemon.js:69:61)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:219:10)
    at Interface.<anonymous> (readline.js:352:12)
    at Array.forEach (native)
→ exit status: 1
henrictrotzig@trotzig:~
⨠
```

(I followed instructions in the [contributing document](https://github.com/Galooshi/import-js/blob/master/CONTRIBUTING.md) in case you want to do the same thing). 

import-js wants a package root of some sort to know how to resolve imports. If it can't find one, it will complain with that error above. 

I think we need to do something to make that error propagate to the client (it doesn't at the moment, leading to that incorrect error about `process not running`). For now, I wonder if you could just [silence the output](https://vi.stackexchange.com/questions/3060/suppress-output-from-a-vim-autocomand)?

**Comment by deltaskelta** [comment]
I’ll work around it for now, good to know though, thanks

-------------------------------
Jeff Willette
jrwillette88@gmail.com

**Comment by deltaskelta** [comment]
actually now I am getting the error even when I am in a project directory, will edit with logs

**Comment by deltaskelta** [comment]
I am not sure how to interpret this log, is it failing because of sqlite3 or is that coming from something else?

**Comment by deltaskelta** [comment]
my last comment was my fault because I changed around the way vim works. everything seems to be working well now. closing
